### ISSUE TITLE
Derive `Clone` for `GlyphCache`

### ISSUE THREAD

**Issue by cybergeek94** [PistonDevelopers/opengl_graphics#115]
Closing this will complete #97.

Requires `freetype::Face` to be `Clone`. (PistonDevelopers/freetype-rs#96)

`data` should change to be `Rc<RefCell<_>>` so that multiple instances of `GlyphCache` can share the same texture cache.

**Comment by bvssvni** [comment]
Sound good.

**Comment by bvssvni** [comment]
One problem is that `Texture` doesn't implement `Clone`.

**Comment by bvssvni** [comment]
We could use `Rc<Character>` in `GlyphCache`. When using `Borrow` we can return a `&Character`.
