### ISSUE TITLE
Move `GlyphCache` to its own repo

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/opengl_graphics#132]
See https://github.com/PistonDevelopers/Piston-Tutorials/pull/47#issuecomment-74654817

FreeType is a bit tricky on some platforms, and it would be nice to have it working for all graphics back-ends.

If we add a trait for creating a texture to piston-texture, then `GlyphCache` can be made generic.

**Comment by Potpourri** [comment]
I would like to do it.
Can you give me a time on it?

**Comment by bvssvni** [comment]
@Potpourri Sure, go ahead!

**Comment by bvssvni** [comment]
One alternative could be to compile `GlyphCache` conditionally with a default feature flag.

**Comment by samestep** [comment]
Is this still planned? I believe I've found a bug in `GlyphCache`; should I
1. submit a pull request to each of [gfx_graphics], [glium_graphics], and [opengl_graphics];
2. wait for `GlyphCache` to be moved to its own repo, then submit one pull request to that repo; or
3. move `GlyphCache` to its own repo and fix the bug in that repo?

If 3, how should I go about doing that? Is there anything additional I should know before I start working on it? Would I need to be added to the PistonDevelopers GitHub organization?

[gfx_graphics]: https://github.com/PistonDevelopers/gfx_graphics
[glium_graphics]: https://github.com/PistonDevelopers/glium_graphics
[opengl_graphics]: https://github.com/PistonDevelopers/opengl_graphics

**Comment by bvssvni** [comment]
This issue is outdated. Closing.

@samestep 1) sounds good, but if you need help I'm available.
