### ISSUE TITLE
"No OpenGL support in video driver" but there is! (Ubuntu 14.04)

### ISSUE THREAD

**Issue by NobbZ** [PistonDevelopers/opengl_graphics#134]
I'm trying to get the `getting-started` to run.

`cargo build` went right through without any errormessages or warnings, but trying `cargo run` or `./target/game` I get the following:

```plain
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "No OpenGL support in video driver"', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:743
```

But OpenGL works for Steam and for many other games, also `glxinfo | grep direct` tells me that `direct rendering: Yes` and `glxdemo`, `glxheads`, and `glxgears` do work.

Just for completeness:

```plain
$ rustc --version
rustc 1.0.0-nightly (6c065fc8c 2015-02-17) (built 2015-02-18)

$ cargo --version
cargo 0.0.1-pre-nightly (918a415 2015-02-17) (built 2015-02-17)

$ uname --all
Linux nobbz-laptop 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ glxinfo | head -5
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
```

Please let me know if you need to know more details or if I need to re-report this behaviour somewhere else.

**Comment by bvssvni** [comment]
Try run some examples from https://github.com/bjz/gl-rs , it might be an issue with gl-rs.

```
cargo run --example static_triangle
```

**Comment by NobbZ** [comment]
I cat't (in a freshly cloned gl-rs folder):

```plain
$ cargo run --example static_triangle
no example target named `static_triangle` to run
```

**Comment by Potpourri** [comment]
Please execute `glxinfo | grep OpenGL`.

**Comment by NobbZ** [comment]
```plain
$ glxinfo| grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.5.0-devel
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.5.0-devel
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
```

**Comment by Potpourri** [comment]
That error is generated by SDL2, this means SDL2 wasn't compiled with GLX support. How you install SDL2?

**Comment by bvssvni** [comment]
There are some instructions here https://github.com/AngryLawyer/rust-sdl2

**Comment by NobbZ** [comment]
SDL itself was installed by simply using `apt-get install libsdl2-dev libfreetype6-dev` as described in the tutorial. Because of the mentionig of GLX-support here in the Thread, I also tried `sudo apt-fast install libsdl2-gfx-dev` and recompiled the getting started, but still the same problem.

Perhaps you can see anything from the output of [`cargo build --verbose`](https://gist.github.com/NobbZ/a4ed8f64c3a5635b6f3e)

**Comment by Potpourri** [comment]
Please check that the linking occurs with systemic SDL2:
```bash
SDL2=(`ldd /home/norbert/projects/rust/getting-started/target/game | grep SDL2`)
echo ${SDL2[@]}
readlink -f ${SDL2[2]}
```

**Comment by NobbZ** [comment]
Since output was somewhat unexpected, I fiddled around ;)

```plain
$ SDL2=(`ldd /home/norbert/projects/rust/getting-started/target/game | grep SDL2`)

$ echo ${SDL2[@]}
libSDL2-2.0.so.0 => /usr/local/lib/libSDL2-2.0.so.0 (0x00007f28f1a4c000)

$ readlink -f ${SDL2[2]}
/home/norbert/projects/rust/getting-started/=>

$ echo ${SDL2[2]}
=>

$ echo ${SDL2[3]}
/usr/local/lib/libSDL2-2.0.so.0

$ readlink -f ${SDL2[3]}
/usr/local/lib/libSDL2-2.0.so.0.4.0
```

And somewhat puzzled why apt should install anything into `/usr/local` I carefully looked through my various source-code folders, and I found a project of a friend of mine, that downloaded, built and installed SDL from source. I didn't care when the script was asking for root, since my friend told me that it will install some build dependencies via apt.

Sorry for the noise!
