### ISSUE TITLE
Custom shaders

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/opengl_graphics#147]
See https://github.com/PistonDevelopers/opengl_graphics/issues/26
- [x] Move `Colored` and `Textured` to separate modules
- [x] Make `Colored` and `Textured` public
- [x] Document `Colored` and `Textured`
- [x] Add constructor `GlGraphics::from_colored_textured`
- [x] Add constructor `Colored::from_vs_fs`
- [x] Add constructor `Textured::from_vs_fs`

**Comment by bvssvni** [comment]
This will allow using a custom vertex or fragment shader, or use a default one from a  `GLSL` version.

**Comment by wldcordeiro** [comment]
I'm taking a stab at this. When you say move colored and textured to separate modules do you mean their own repos or modules within the opengl_graphics package?

**Comment by bvssvni** [comment]
I mean modules within the package.

**Comment by wldcordeiro** [comment]
Ah I see, alright. I'll try it out, any suggest for a module name? `shader.rs`?

**Comment by bvssvni** [comment]
Yeah, `shader.rs` is good.

**Comment by wldcordeiro** [comment]
Could you describe what the constructors `from_vs_fs` should do?

**Comment by bvssvni** [comment]
They should take the source for vertex and fragment shaders.

**Comment by bvssvni** [comment]
Could use `Shaders` from shader_version https://github.com/PistonDevelopers/shader_version/blob/master/src/lib.rs#L16

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/opengl_graphics/pull/265
