### ISSUE TITLE
Fix Texture::from_memory_alpha()

### ISSUE THREAD

**Issue by gregkatz** [PistonDevelopers/opengl_graphics#182]
`from_memory_alpha()` didn't work for me without changing `pixels.extend(vec![255; 3])` to `pixels.extend(vec![0; 3])`.

Without that change, the texture seems to be all white regardless of the alpha value supplied. I may also be misunderstanding how textures work as I've never worked with textures before.

I can submit a pull request, but you'll have to forgive any mistakes, I've never contributed to an open source project before.

**Comment by bvssvni** [comment]
The color you render a texture gets multiplied with the color in the texture, meaning that "white" allows you to pick any color. Perhaps you did not enable alpha blending?

**Comment by gregkatz** [comment]
Oh, I think I understand now. I was generating a sprite directly from the texture, without multiplying it by anything.
