### ISSUE TITLE
Implement texture filtering

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/opengl_graphics#217]
Depends on https://github.com/PistonDevelopers/texture/issues/32

Currently uses `gl::LINEAR` for both `gl::TEXTURE_MIN_FILTER` and `gl::TEXTURE_MAG_FILTER`. New behavior:
- [ ] Map `TextureSettings::get_mag` for `gl::TEXTURE_MAG_FILTER`
- [ ] Add a function that maps `TextureSettings::get_generate_mipmaps`, `TextureSettings::get_min` and `TextureSettings::get_mipmap` for `gl::TEXTURE_MIN_FILTER`
- [ ] If `TextureSettings::get_generate_mipmaps` is `true`, call [glGenerateMipmap](https://www.opengl.org/wiki/GLAPI/glGenerateMipmap)

For min filter, use this table:

| Param Setting | Linear within mip-level | Has mipmapping | Linear between mip-levels |
| --- | --- | --- | --- |
| GL_NEAREST | No | No |  |
| GL_LINEAR | Yes | No |  |
| GL_NEAREST_MIPMAP_NEAREST | No | Yes | No |
| GL_LINEAR_MIPMAP_NEAREST | Yes | Yes | No |
| GL_NEAREST_MIPMAP_LINEAR | No | Yes | Yes |
| GL_LINEAR_MIPMAP_LINEAR | Yes | Yes | Yes |

**Comment by nanotech** [comment]
This was fixed by #221.
