### ISSUE TITLE
sRGB color space problem?

### ISSUE THREAD

**Issue by Rydgel** [PistonDevelopers/opengl_graphics#264]
Hello,

It seems I have an issue to display my texture with the correct colours. It seems like everything I tried didn't change anything.

Here is a few excerpt of how I load the texture and draw it:

```rust
use opengl_graphics::{GlGraphics, Texture, TextureSettings};
use graphics::{Context, Transformed};
use graphics::draw_state::DrawState;
use graphics::Image;
// ...
let mut texture_settings = TextureSettings::new();
texture_settings.set_convert_gamma(true);
texture_settings.set_compress(true);
let texture = Texture::from_image(&img, &texture_settings);
// ...
// in the drawing method
Image::new().draw(&self.texture, &DrawState::new_alpha(), transf, gl);
```

So changing the `set_convert_gamma` value to `false` or `true` does nothing.
Creating the Window with `.srgb(true)` or `.srgb(false)` does nothing.

I'm on OS X. I'm using Rust nightly `rustc 1.16.0-nightly (24055d0f2 2017-01-31)`
Cargo packages:
```
[dependencies]
itertools = "0.5.9"
piston = "0.31.3"
piston_window = "0.64.0"
piston2d-graphics = "0.21.1"
pistoncore-sdl2_window = "0.40.0"
piston2d-opengl_graphics = "0.40.0"
rand = "0.3.15"
find_folder = "0.3.0"
image = "0.12.2"
```

![](http://i.imgur.com/RyNTnnS.png)

And here is the texture image itself

![scavengers_spritesheet](https://cloud.githubusercontent.com/assets/6583/22665855/a17c043e-ecb6-11e6-9a01-74870c1a8bd8.png)

**Comment by bvssvni** [comment]
Seems that none of the backends implements gamma conversion for textures.

**Comment by Rydgel** [comment]
Maybe I can try to convert my texture with something like `gamma_srgb_to_linear`?

**Comment by bvssvni** [comment]
Yes, you can do this manually.

I wonder why it shows wrong colors, because it seems your texture is in sRGB. This should be enabled here https://github.com/PistonDevelopers/opengl_graphics/blob/master/src/back_end.rs#L338, converting to linear color space in the shaders, and back when writing to the frame buffer.

**Comment by Rydgel** [comment]
Yeah I saw that, it's weird. I even tried with other images, same problem.

**Comment by Rydgel** [comment]
I even tried several Window library, currently suing SDL2Window, but tried GLFW and Glut with the same result.

**Comment by Rydgel** [comment]
Doing a gamma_srgb_to_linear conversion on my texture fixes the issue for me.
It's weird since it seems that the invert is done inside the drawing function.

<img width="651" alt="" src="https://cloud.githubusercontent.com/assets/6583/22667737/5b8bef4a-ecbe-11e6-9959-80e24aef8e09.png">

**Comment by adfaure** [comment]
Hello,
I have the same issue here.

I will do it manually too, but will it be fixed in a future release ?
Thanks a lot !

**Comment by expenses** [comment]
@Rydgel @adfaure Would you mind sharing the code that you used to perform the conversion? I'm having trouble with this step.

**Comment by Rydgel** [comment]
@expenses Doing this basically: https://github.com/Rydgel/rust-rogue/blob/b09400daec0a84a82d6b357e9ffa5f55c68afd5c/src/drawings/sprites.rs#L64

**Comment by expenses** [comment]
@Rydgel So I was on the right track! Thank you very much!

**Comment by Aerolivier** [comment]
Am I right in thinking this can be solved by tagging the texture data with the `GL_SRGB8` or `GL_SRGB8_ALPHA8` formats? ( according to https://www.khronos.org/opengl/wiki/Image_Format#sRGB_colorspace )

As far as I understand, quantising the linear values to 8 bits leads to a loss of integrity in the image ( as demonstrated at http://tulrich.com/webgl/rgb/linear_vs_srgb.html ).

I'd like to fix this, but I'm not familiar with the code base. Any pointers or should I just start getting stuck in?
