### ISSUE TITLE
Texture::from_path should have a TextureSettings arg.

### ISSUE THREAD

**Issue by Zennii** [PistonDevelopers/opengl_graphics#270]
I noticed that [Texture::from_path](https://github.com/PistonDevelopers/opengl_graphics/blob/master/src/texture.rs#L105) does not accept an argument for TextureSettings, but it's already using the defaults when calling [Texture::from_image](https://github.com/PistonDevelopers/opengl_graphics/blob/master/src/texture.rs#L122). I switched things around for my own purposes and it seems to work fine.

**Comment by robo-hamburger** [comment]
Should `Texture::from_path`'s new signature include the TextureSettings or should there be a new method `Texture::from_path_with_settings` or something?
