### ISSUE TITLE
Support for WebGL shaders is restricted to emscripten targets.

### ISSUE THREAD

**Issue by AGausmann** [PistonDevelopers/opengl_graphics#318]
See for example: https://github.com/PistonDevelopers/opengl_graphics/blob/master/src/back_end.rs#L68

Generally, the expression `cfg!(target_os = "emscripten")` is used to enable WebGL-specific functionality, but it is possible to use WebGL in `wasm32-unknown-unknown`. I'm working on WebGL support for Piston specifically on this target, so it would be nice to support it as well.

**Comment by AGausmann** [comment]
The condition that I'm using in my testing is `cfg!(target_arch = "wasm32")`, but that's not correct either. WebAssembly programs can link native libraries including the system OpenGL implementation, which would not work in this case.

I think the best thing to do is let the user decide. In my opinion, this should happen at compile-time using feature flags, but it could also be a configuration option at runtime.

**Comment by bvssvni** [comment]
I think Cargo features is fine.

**Comment by AGausmann** [comment]
What is your preference regarding backwards compatibility? Based on semver this project is still unstable, but I'd at least like to avoid unnecessary breaking changes.

It's possible to leave the Emscripten target detection alone and logically OR with the feature, with a conditional deprecation warning behind `#[cfg(and(not(feature = "webgl"), target_os = "emscripten")]`. On the other hand, it's not a problem to always enable WebGL for Emscripten targets, as that is the OpenGL implementation on those targets.

**Comment by AGausmann** [comment]
Okay, I've implemented it based on the feedback I got here and created #319
