### ISSUE TITLE
Opengl_graphics 0.71.0 Doesn't implement graphics::clear()

### ISSUE THREAD

**Issue by cm16161** [PistonDevelopers/opengl_graphics#322]
When using piston2d-opengl_graphics 0.71.0, I get the following error message when attempting to create a simple screen and clear it with a white background.
graphics::clear([1.0;4], g);
   |                 ^^^^^^^^^^^^^^^ the trait `graphics::Graphics` is not implemented for `opengl_graphics::GlGraphics`

However, when using piston2d-opengl_graphics 0.70.0, this issue doesn't happen.
Thanks

**Comment by bvssvni** [comment]
Maybe there are different versions of `piston2d-graphics`? Check Cargo.lock

**Comment by cm16161** [comment]
That was it! 
piston2d-openg_gl 0.71.0 relies on piston2d-graphics 0.36.0
I hadn't updates that, thanks!
