### ISSUE TITLE
compile_shader: ERROR: 0:1: '' :  version '120' is not supported

### ISSUE THREAD

**Issue by TyOverby** [PistonDevelopers/opengl_graphics#63]
When trying to convert a working example from using opengl 3.2 to 1.2.0, I get this error immediately.

```
task '<main>' failed at 'compile_shader: ERROR: 0:1: '' :  version '120' is not supported
ERROR: 0:2: '' :  #version required and missing.
ERROR: 0:2: 'attribute' : syntax error syntax error
', src/gl_back_end.rs:168
```

My computer does in fact support 1.2.0, so I am guessing that the issue that I'm running into is the same as the one found here: http://gamedev.stackexchange.com/questions/22958/why-does-my-glsl-1-20-shader-not-work-with-an-opengl-4-0-driver

**Comment by bvssvni** [comment]
Is this still a problem?

**Comment by TyOverby** [comment]
I don't know.  I don't think I'll be able to check either, so I'll close this.
