### ISSUE TITLE
`GlyphCache` improvements

### ISSUE THREAD

**Issue by cybergeek94** [PistonDevelopers/opengl_graphics#97]
- [x] Method to pre-load all characters for a given font size, perhaps `preload(&mut self, &[char])`
- [x] `preload_printable_ascii(&mut self)`
- [x] `opt_character` method that returns `Option<&Character>` and takes `&self`
- [x] Implement `Clone` (so it doesn't have to be reloaded from a file to get another copy, not sure how this would interact with the FFI parts)
- [x]  ~~Consider thread-safety when contained in a `Mutex` or `RWLock`; the latter would be great with preloading so cached characters can be fetched with a concurrent read lock (if that's safe)~~

**Comment by bvssvni** [comment]
Done.
